---
title: "datos-investigacion"
author: "JJ Merelo"
date: "26/11/2015"
output: html_document
---
#Resultados de investigación

```{r, echo=FALSE, message=FALSE,results='hide',warning=FALSE}
investigacion.UGR <- read.csv('../data/estadisticasbasicastodas.csv')
```
## Introducción

UGR es una de las principales universidades de Andalucía en investigación. Los datos extraídos del [portal de datos abiertos](http://opendata.ugr.es) nos indican su evolución en los últimos años. Como resultado básico de esta investigación, tenemos los trabajos publicados.

## Publicaciones
```{r, echo=FALSE, message=FALSE,results='hide',warning=FALSE}
library(ggplot2)
library(reshape2)
publicaciones.UGR <- investigacion.UGR[investigacion.UGR$Tipo.de.Estadística=="Publicaciones ISI",]
publicaciones.UGR.year <- melt(publicaciones.UGR,id.vars=1:2,variable.name="year")
publicaciones.UGR.year$value <- as.integer(publicaciones.UGR.year$value)
pubs.WOS <- publicaciones.UGR.year[publicaciones.UGR.year$Denominación == "No. pub. WoS (Thomson)",]
pubs.WOS.citables <- publicaciones.UGR.year[publicaciones.UGR.year$Denominación == "No. pub. Citables  WoS (Thomson)",]
ggplot()+geom_point(data=pubs.WOS,aes(x=year,y=value,color='Todas'))+geom_point(data=pubs.WOS.citables,aes(x=year,y=value,color='Citables'))
```

